---
# Documentation: https://pre-commit.com/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: jira-ticket
        name: check for jira ticket
        language: pygrep
        entry: "([A-Z]+-[0-9]+|TRIVIAL)"
        args: [--multiline, --negate]
        stages: [commit-msg]
