---
# DOCKER COMPOSE TEMPLATE

services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

# Databases
  postgres:
    image: postgres:13.2
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: cloudtalk
      POSTGRES_USER: cloudtalk
      POSTGRES_PASSWORD: cloudtalk
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mariadb:
    image: 233281872604.dkr.ecr.eu-central-1.amazonaws.com/ct-mariadb:cloudtalk-stage-data
    ports:
      - '3306:3306'
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: cloudtalk
      MARIADB_USER: cloudtalk
      MARIADB_PASSWORD: password
    restart: on-failure
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
    volumes:
      - mariadb_data:/bitnami/mariadb

# Kafka
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=user
      - ZOO_SERVER_PASSWORDS=password
      - ZOO_CLIENT_USER=user
      - ZOO_CLIENT_PASSWORD=password
    healthcheck:
      test: [ "CMD", "sh", "-c", "nc -nz 127.0.0.1 2181" ]
      interval: 5s
      timeout: 60s
      retries: 120

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true

      - KAFKA_CFG_LISTENERS=EXTERNAL://:9092,INTERNAL://:9091
      - KAFKA_CFG_ADVERTISED_LISTENERS=EXTERNAL://127.0.0.1:9092,INTERNAL://kafka:9091
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:SASL_SSL,CLIENT:SASL_SSL

      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL_PLAINTEXT
      - KAFKA_ZOOKEEPER_USER=user
      - KAFKA_ZOOKEEPER_PASSWORD=password

      - KAFKA_CLIENT_USERS=user
      - KAFKA_CLIENT_PASSWORDS=password

      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - BITNAMI_DEBUG=true

    healthcheck:
      test:
        [
          "CMD",
          "/opt/bitnami/kafka/bin/kafka-topics.sh",
          "--list",
          "--bootstrap-server",
          "kafka:9091"
        ]
      interval: 15s
      timeout: 40s
      retries: 5

  init-kafka:
    image: 'bitnami/kafka:latest'
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      /opt/bitnami/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9091 --replication-factor 1 --partitions 1 --topic TOPIC_NAME
      "

volumes:
  postgres_data: { }
  mariadb_data: { }
