# GitHub action to check Pull Request title and commit messages if they include JIRA ticket ID
name: check-jira-ticket-id.yaml

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  # checks if Jira ID is in the title of the PR
  check-jira-id-usage:
    name: Check usage of Jira ID
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: [self-hosted, runner, mgmt, base]
    steps:
      - name: Check Jira ID in the PR title
        uses: CloudTalk-io/action-check-pr-title@main
        with:
          jiraUrl: ${{ vars.JIRA_URL }}
          jiraUsername: ${{ secrets.JIRA_USERNAME }}
          jiraToken: ${{ secrets.JIRA_TOKEN }}

      # checks if messages of PR includes Jira ID in their name
      - name: Get PR Commits
        id: 'get-pr-commits'
        uses: CloudTalk-io/get-pr-commits@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Jira ID in PR's commit messages
        uses: CloudTalk-io/commit-message-checker-with-regex@master
        with:
          commits: ${{ steps.get-pr-commits.outputs.commits }}
